### ISSUE TITLE
Where is Mipha-1.6B?

### ISSUE THREAD

**Issue by JohannesVod** [zhuyiche/llava-phi#15]
Hi, 

is there a way to get the model weights from mipha-1.6B ? Currently i only see the 3B model, but i need the smaller one because i want a really small and fast model that i can train on domain specific data.

**Comment by JohannesVod** [comment]
@JLM-Z😥

**Comment by JohannesVod** [comment]
@JLM-Z @zhuyiche I can paypal you 5 dollar if you do it

**Comment by JLM-Z** [comment]
I'm sorry for my latter reply. I'm going to make the Mipha-1.6B weights public for free this week. However, the exact release date cannot be determined at the moment, as the Pythia code has not been integrated into this codebase, even though only a few lines of code need to be changed to run it stably. Additionally, the disk storing the model weights is undergoing physical migration. Please understand.

**Comment by JohannesVod** [comment]
@JLM-Z Thank you! Also, very nice work tbh

**Comment by JLM-Z** [comment]
I have updated this codebase for phi1.5, and the weigths of Mipha-phi1.5 are [here](https://huggingface.co/zhumj34/Mipha-phi1_5-1.6B). 
A simple example would be like this:
```
python mipha/serve/cli.py  --model-path zhumj34/Mipha-phi1_5-1.6B --conv-mode phi --image-file ./mipha/serve/examples/extreme_ironing.jpg
```

**Comment by JohannesVod** [comment]
thank you very much!
