### ISSUE TITLE
Request for model weights

### ISSUE THREAD

**Issue by pipilurj** [zhuyiche/llava-phi#3]
Dear authors,
Thanks for the great work! I wonder if you have any plans on releasing the model weights any time soon? Thanks a lot!

**Comment by zhuyiche** [comment]
Hello, we will be releasing the model weights very soon.

**Comment by vikashraja24** [comment]
Is there a timeline for releasing the model weights?

**Comment by bluesky333** [comment]
Although it is noted that the model is released 15th of January, I still don't see the link for the weights.

**Comment by bluesky333** [comment]
We are trying to finetune this model for medical domain to include in our manuscript which is due in a week.
Please share the model weights with us.

**Comment by zhuyiche** [comment]
We have released the model weights, thank you for your patience.
